### ISSUE TITLE
HDMI Audio: Solved!

### ISSUE THREAD

**Issue by DottoreTozzi** [novaspirit/macpanda#3]
Toleda solved the HDMI Audio problem with me assisting him:
https://github.com/toleda/audio_CloverHDMI/issues/23

This solution is based on Version 1.2 of your Clover package.
The changes:
Added AppleHDA.kext
Added FakePCIID_Intel_HDMI_Audio.kext

config.plist -> devices -> properties:
added these patches:
framebuffer-con1-enable = 01000000
framebuffer-con1-flags = 87010000
framebuffer-con1-type = 00080000

That should be it.

[config.plist.zip](https://github.com/novaspirit/macpanda/files/2573475/config.plist.zip)

**Comment by nichtsooft** [comment]
Could you be so kind and post a complete package including all files from the clover-folder?

regards

**Comment by novaspirit** [comment]
will be adding this soon!! thanks so much!!

**Comment by DottoreTozzi** [comment]
I want to leave that to @novaspirit .

You can use the attached config.plist above.

The FakePCIID_Intel_HDMI_Audio.kext can be found in the 2.0beta release.

For AppleHDA.kext:
Right Click on the Mac OS Installer, "Show Package Contents".
Browse to Content -> Shared Support.
Mount InstallESD.dmg.
Open it in Finder, navigate to:
Contents/Shared Support.
Mount BaseSystem.dmg.
Open and navigate to System/Library/Extensions/
There you'll find it.
Copy it over to EFI/Clover/kexts/Other.

@novaspirit : 
You're welcome! Thank YOU for all your work involved in this!
And many thanks to @toleda for all his patience with me on this one.

**Comment by DottoreTozzi** [comment]
One more thing:
iDisplay Audio Connect has to be enabled in BIOS, other than shown in the youtube video.
Else, it won't work, not even in Windows or Linux.

**Comment by nichtsooft** [comment]
@DottoreTozzi Das kann ich selbstverständlich nachvollziehen. / I totally understand that!
mille grazie dottore! :ok_hand:

**Comment by novaspirit** [comment]
fresh install on 10.14.1 and HDMI audio working! thankssss everyone! putting together the new files now

**Comment by nichtsooft** [comment]
Is it essential to reinstall!?
Isn't it enough to copy the clover-files over!? ^^
